apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  SPRING_DATA_MONGODB_URI: "mongodb://mongodb:27017/employeedb"
  SERVER_PORT: "8080"
  REACT_APP_API_URL: "http://backend-service:8085/api"
